# Generated by Django 2.2.2 on 2019-06-09 08:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.TextField(null=True)),
                ('environments', django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True)),
                ('requests', django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=200)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'domain',
            },
        ),
        migrations.CreateModel(
            name='InfraDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=200)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'infra_details',
            },
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(max_length=200)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(auto_now_add=True)),
                ('output', models.TextField(null=True)),
                ('delivery_log', models.TextField(null=True)),
                ('status', models.CharField(max_length=15, null=True)),
                ('job_data', django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=200)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'job_history',
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=200)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'measure',
            },
        ),
    ]
