# Generated by Django 2.2.2 on 2019-06-09 08:16

import authentication.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='First Name of user', max_length=200, null=True)),
                ('last_name', models.CharField(help_text='Last Name of user', max_length=200, null=True)),
                ('username', models.CharField(help_text='Username for the user', max_length=200, unique=True)),
                ('email', models.EmailField(help_text='Email of the user', max_length=200, unique=True)),
                ('login_attempts', models.IntegerField(default=0, help_text='To track no of invalid login attempts')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', authentication.models.UserAccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email of the user', max_length=200)),
                ('valid_upto', models.DateTimeField(help_text='DateTime valid upto')),
                ('expired', models.BooleanField(default=False, help_text='If True - Link can not be used, False - Link can be used')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Reset link creation date')),
            ],
            options={
                'db_table': 'forgot_password',
            },
        ),
    ]
